param(
    [string]$ObjPath = "C:\Users\lkwelf3f3\Desktop\glamour\src\assets\models\model.obj",
    [string]$OutHeader = "C:\Users\lkwelf3f3\Desktop\glamour\src\assets\model_data.hpp",
    [string]$PngPath = "C:\Users\lkwelf3f3\Desktop\glamour\src\assets\models\base_color_texture.png",
    [string]$OutPngHeader = "C:\Users\lkwelf3f3\Desktop\glamour\src\assets\model_tex.hpp",
    [float]$TargetHeight = 1.7
)

$ErrorActionPreference = "Stop"

function Write-HeaderFile {
    param([string]$Path, [string]$PragmaName, [string]$Content)
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("#pragma once")
    $lines.Add("")
    $lines.Add("// generated by convert_model.ps1 - do not edit")
    $lines.Add("")
    $Content
    $sb = [System.Text.StringBuilder]::new()
    foreach ($l in $lines) {
        $sb.Append($l).Append("`n") | Out-Null
    }
    [System.IO.File]::WriteAllText($Path, $sb.ToString())
}

function Split-B64 {
    param([string]$B64)
    $chunks = New-Object System.Collections.Generic.List[string]
    $len = $B64.Length
    $i = 0
    while ($i -lt $len) {
        $n = [Math]::Min(60000, $len - $i)
        $chunks.Add($B64.Substring($i, $n))
        $i += $n
    }
    return $chunks
}

function Floats-To-B64 {
    param([float[]]$Floats)
    $n = $Floats.Length
    $bytes = New-Object byte[] ($n * 4)
    $h = [System.BitConverter]::GetBytes([double]0)
    for ($i = 0; $i -lt $n; $i++) {
        $b = [System.BitConverter]::GetBytes([float]$Floats[$i])
        [System.Buffer]::BlockCopy($b, 0, $bytes, $i * 4, 4)
    }
    return [Convert]::ToBase64String($bytes)
}

function Ints-To-B64 {
    param([int[]]$Ints)
    $n = $Ints.Length
    $bytes = New-Object byte[] ($n * 4)
    for ($i = 0; $i -lt $n; $i++) {
        $b = [System.BitConverter]::GetBytes([int]$Ints[$i])
        [System.Buffer]::BlockCopy($b, 0, $bytes, $i * 4, 4)
    }
    return [Convert]::ToBase64String($bytes)
}

# ---------- parse OBJ ----------
$pos = New-Object System.Collections.Generic.List[float]
$nrm = New-Object System.Collections.Generic.List[float]
$uvs = New-Object System.Collections.Generic.List[float]

$sr = New-Object System.IO.StreamReader($ObjPath)
try {
    while ($null -ne ($line = $sr.ReadLine())) {
        if ($line.Length -eq 0) { continue }
        $c = $line[0]
        if ($c -eq 'v') {
            if ($line.Length -gt 1 -and $line[1] -eq ' ') {
                $p = $line.Substring(2).Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
                $pos.Add([float]$p[0]); $pos.Add([float]$p[1]); $pos.Add([float]$p[2])
            } elseif ($line.Length -gt 2 -and $line[1] -eq 'n' -and $line[2] -eq ' ') {
                $p = $line.Substring(3).Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
                $nrm.Add([float]$p[0]); $nrm.Add([float]$p[1]); $nrm.Add([float]$p[2])
            } elseif ($line.Length -gt 2 -and $line[1] -eq 't' -and $line[2] -eq ' ') {
                $p = $line.Substring(3).Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
                $uvs.Add([float]$p[0]); $uvs.Add([float]$p[1])
            }
        }
    }
} finally {
    $sr.Close()
}

# ---------- reindex (v/vt/vn may be independent index spaces) ----------
$vert_map = New-Object 'System.Collections.Generic.Dictionary[uint64,int]' -ArgumentList 1048576
$npos = New-Object System.Collections.Generic.List[float]
$nnrm = New-Object System.Collections.Generic.List[float]
$nuvs = New-Object System.Collections.Generic.List[float]
$tri = New-Object System.Collections.Generic.List[int]

$sr = New-Object System.IO.StreamReader($ObjPath)
try {
    while ($null -ne ($line = $sr.ReadLine())) {
        if ($line.Length -lt 2 -or $line[0] -ne 'f' -or $line[1] -ne ' ') { continue }
        $p = $line.Substring(2).Split(' ', [System.StringSplitOptions]::RemoveEmptyEntries)
        $face = New-Object int[] ($p.Length)
        for ($k = 0; $k -lt $p.Length; $k++) {
            $parts = $p[$k].Split('/')
            $vi = [int]$parts[0] - 1
            $ti = $vi
            $ni = $vi
            if ($parts.Length -ge 2 -and $parts[1].Length -gt 0) { $ti = [int]$parts[1] - 1 }
            if ($parts.Length -ge 3 -and $parts[2].Length -gt 0) { $ni = [int]$parts[2] - 1 }
            $key = ([uint64]$vi -shl 42) -bor ([uint64]$ti -shl 21) -bor ([uint64]$ni -band 0x1FFFFF)
            $idx = 0
            if (-not $vert_map.TryGetValue($key, [ref]$idx)) {
                $idx = $npos.Count / 3
                $vert_map[$key] = $idx
                $npos.Add($pos[$vi*3]); $npos.Add($pos[$vi*3+1]); $npos.Add($pos[$vi*3+2])
                $nnrm.Add($nrm[$ni*3]); $nnrm.Add($nrm[$ni*3+1]); $nnrm.Add($nrm[$ni*3+2])
                $nuvs.Add($uvs[$ti*2]); $nuvs.Add($uvs[$ti*2+1])
            }
            $face[$k] = $idx
        }
        if ($face.Length -eq 3) {
            $tri.Add($face[0]); $tri.Add($face[1]); $tri.Add($face[2])
        } elseif ($face.Length -eq 4) {
            $tri.Add($face[0]); $tri.Add($face[1]); $tri.Add($face[2])
            $tri.Add($face[0]); $tri.Add($face[2]); $tri.Add($face[3])
        }
    }
} finally {
    $sr.Close()
}

$pos = $npos
$nrm = $nnrm
$uvs = $nuvs
$vcount = $pos.Count / 3
$tcount = $tri.Count / 3
Write-Host "verts=$vcount tris=$tcount uvs=$($uvs.Count/2) nrms=$($nrm.Count/3)"

# ---------- normalize (center + scale to TargetHeight) ----------
$minX = [float]::MaxValue; $minY = [float]::MaxValue; $minZ = [float]::MaxValue
$maxX = [float]::MinValue; $maxY = [float]::MinValue; $maxZ = [float]::MinValue
for ($i = 0; $i -lt $pos.Count; $i += 3) {
    if ($pos[$i] -lt $minX) { $minX = $pos[$i] }
    if ($pos[$i] -gt $maxX) { $maxX = $pos[$i] }
    if ($pos[$i+1] -lt $minY) { $minY = $pos[$i+1] }
    if ($pos[$i+1] -gt $maxY) { $maxY = $pos[$i+1] }
    if ($pos[$i+2] -lt $minZ) { $minZ = $pos[$i+2] }
    if ($pos[$i+2] -gt $maxZ) { $maxZ = $pos[$i+2] }
}
$cx = ($minX + $maxX) / 2.0
$cy = ($minY + $maxY) / 2.0
$cz = ($minZ + $maxZ) / 2.0
$dx = $maxX - $minX; $dy = $maxY - $minY; $dz = $maxZ - $minZ
$maxd = [Math]::Max($dx, [Math]::Max($dy, $dz))
if ($maxd -le 0) { $maxd = 1 }
$scale = $TargetHeight / $maxd
Write-Host "bbox min=$minX,$minY,$minZ max=$maxX,$maxY,$maxZ center=$cx,$cy,$cz scale=$scale"
for ($i = 0; $i -lt $pos.Count; $i += 3) {
    $pos[$i] = ($pos[$i] - $cx) * $scale
    $pos[$i+1] = ($pos[$i+1] - $cy) * $scale
    $pos[$i+2] = ($pos[$i+2] - $cz) * $scale
}

$posArr = $pos.ToArray()
$nrmArr = $nrm.ToArray()
$uvsArr = $uvs.ToArray()
$triArr = $tri.ToArray()

# ---------- write model header ----------
$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("#pragma once")
$lines.Add("")
$lines.Add("// generated by convert_model.ps1 - do not edit")
$lines.Add("")
$lines.Add("#include <cstddef>")
$lines.Add("")
$lines.Add("static const int g_model_vert_count = $vcount;")
$lines.Add("static const int g_model_tri_count = $tcount;")
$lines.Add("static const size_t g_model_pos_len = $($posArr.Length);")
$lines.Add("static const size_t g_model_nrm_len = $($nrmArr.Length);")
$lines.Add("static const size_t g_model_uvs_len = $($uvsArr.Length);")
$lines.Add("static const size_t g_model_tri_len = $($triArr.Length);")
$lines.Add("")
$lines.Add("static const char* const g_model_pos_b64 =")
foreach ($c in (Split-B64 (Floats-To-B64 $posArr))) { $lines.Add("    `"$c`"") }
$lines.Add("    ;")
$lines.Add("")
$lines.Add("static const char* const g_model_nrm_b64 =")
foreach ($c in (Split-B64 (Floats-To-B64 $nrmArr))) { $lines.Add("    `"$c`"") }
$lines.Add("    ;")
$lines.Add("")
$lines.Add("static const char* const g_model_uvs_b64 =")
foreach ($c in (Split-B64 (Floats-To-B64 $uvsArr))) { $lines.Add("    `"$c`"") }
$lines.Add("    ;")
$lines.Add("")
$lines.Add("static const char* const g_model_tri_b64 =")
foreach ($c in (Split-B64 (Ints-To-B64 $triArr))) { $lines.Add("    `"$c`"") }
$lines.Add("    ;")
$lines.Add("")

$sb = [System.Text.StringBuilder]::new()
foreach ($l in $lines) { $sb.Append($l).Append("`n") | Out-Null }
[System.IO.File]::WriteAllText($OutHeader, $sb.ToString())
Write-Host "wrote $OutHeader ($([Math]::Round((Get-Item $OutHeader).Length/1MB,2)) MB)"

# ---------- write png header ----------
if ($PngPath -and (Test-Path -LiteralPath $PngPath)) {
    $png = [System.IO.File]::ReadAllBytes($PngPath)
    $b64 = [Convert]::ToBase64String($png)
    $lines2 = New-Object System.Collections.Generic.List[string]
    $lines2.Add("#pragma once")
    $lines2.Add("")
    $lines2.Add("// generated by convert_model.ps1 - do not edit")
    $lines2.Add("")
    $lines2.Add("#include <cstddef>")
    $lines2.Add("")
    $lines2.Add("static const size_t g_model_png_len = $($png.Length);")
    $lines2.Add("")
    $lines2.Add("static const char* const g_model_png_b64 =")
    foreach ($c in (Split-B64 $b64)) { $lines2.Add("    `"$c`"") }
    $lines2.Add("    ;")
    $lines2.Add("")
    $sb2 = [System.Text.StringBuilder]::new()
    foreach ($l in $lines2) { $sb2.Append($l).Append("`n") | Out-Null }
    [System.IO.File]::WriteAllText($OutPngHeader, $sb2.ToString())
    Write-Host "wrote $OutPngHeader ($([Math]::Round((Get-Item $OutPngHeader).Length/1MB,2)) MB)"
}
